version: '3.7'

services:
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile 
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
    network_mode: "host"
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_NAME: postgres
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports: 
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin


volumes:
  postgres_data:
  pgadmin:
