# Generated by Django 3.2.9 on 2022-01-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'bussiness')], default=1),
        ),
    ]
