# Generated by Django 3.2.9 on 2022-01-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='image_url',
            field=models.URLField(default='https://images.pexels.com/photos/3992870/pexels-photo-3992870.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260'),
            preserve_default=False,
        ),
    ]
