# Generated by Django 3.2.9 on 2022-01-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_bussiness_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='dsecription',
            field=models.CharField(default='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras pellentesque nibh eget justo tincidunt aliquam. Phasellus quis porttitor arcu. Proin rhoncus turpis nisi, sed accumsan diam feugiat vitae. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vestibulum pharetra turpis in porttitor. Mauris sit amet malesuada urna.', max_length=500),
            preserve_default=False,
        ),
    ]
