# Generated by Django 3.2.9 on 2022-01-12 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_bussiness_dsecription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bussiness',
            old_name='dsecription',
            new_name='description',
        ),
    ]
